--CREATE DATABASE btr
--    ON (
--        NAME = 'btr_data',
--        FILENAME = 'd:\database\btr\btr_data.mdf')
--        LOG ON (
--        NAME = 'btr_log',
--        FILENAME = 'd:\database\btr\btr_log.ldf')
--GO
